name: Publish Package
run-name: ${{ github.workflow }}${{ inputs.dry-run && ' (dry run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run (no publish)
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  check:
    name: Check before publish
    runs-on: ubuntu-22.04
    steps:
      - name: Check run conditions
        if: github.ref != 'refs/heads/main' && inputs.dry-run == false
        run: |
          echo "::error::Can only publish from the main branch"
          exit 1
  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.11.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint --if-present
      - name: Run test
        run: npm run test --if-present
      - name: Run build
        run: npm run build --if-present
      - name: Run package
        id: run-package
        run: echo "filename=$(npm pack -q)" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.run-package.outputs.filename }}
          path: ${{ steps.run-package.outputs.filename }}
          if-no-files-found: error
    outputs:
      filename: ${{ steps.run-package.outputs.filename }}
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-22.04
    needs: [build]
    if: inputs.dry-run == false
    env:
      ARTIFACT_FILENAME: ${{ needs.build.outputs.filename }}
    environment:
      name: npm
      url: https://www.npmjs.com/package/read-vietnamese-number
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ env.ARTIFACT_FILENAME }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.11.0'
          registry-url: https://registry.npmjs.org/
      - name: Run publish
        run: npm publish ${{ env.ARTIFACT_FILENAME }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
